### ISSUE TITLE
将80端口更换到8080端口的问题

### ISSUE THREAD

**Issue by xsjqqq123** [clangcn/ngrok-one-key-install#9]
请问一下将80端口更换到8080端口，有什么更好的方式？
我现在在/etc/apache2/sites-enabled/目录建立ngrok_proxy.conf
写入如下内容：
<VirtualHost *:80>
  ServerName [sosoblog.top](url)
  ProxyPreserveHost On
  ProxyRequests Off
  ProxyPass / http://myip:8080
  ProxyPassReverse / http://myip:8080
</VirtualHost>

这样访问ServerName 时，会转发到ngrok，从而正常工作，但这样的情况是，每个域名我都要加一次这样的代理，有点麻烦，有更好的方法吗？

**Comment by clangcn** [comment]
试一下这个，百度看到的
有个叫”ServerAlias“的东西可以用
其实可以这样：

<VirtualHost *:80>
ServerAdmin i@kuigg.com
DocumentRoot /www/kuigg.com
ServerName kuigg.com
ServerAlias  www.kuigg.com  abc.kuigg.com
</VirtualHost>


要绑多少个域名都可以写在 ServerAlias   后面，用空格隔开即可
